### ISSUE TITLE
Failed to launch dev server on Windows

### ISSUE THREAD

**Issue by MatteoGauthier** [tinacms/tina-cloud-starter#52]
Got this error 

```
Started Filesystem GraphQL server on port: 4001
Generating Tina config
Cannot find module 'D:\\Dev\\WebDev\\NextJS\\tina-cloud-starter\\.tina\\__generated__\\temp/schema.js'
Require stack:
- D:\Dev\WebDev\NextJS\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\dist\index.js
- D:\Dev\WebDev\NextJS\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\bin\tina-gql, exiting...
D:\Dev\WebDev\NextJS\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\dist\index.js:1
Error: Cannot find module 'D:\\Dev\\WebDev\\NextJS\\tina-cloud-starter\\.tina\\__generated__\\temp/schema.js'
Require stack:
- D:\Dev\WebDev\NextJS\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\dist\index.js
- D:\Dev\WebDev\NextJS\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\bin\tina-gql
    at compile (D:\Dev\WebDev\NextJS\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\dist\index.js:275:22)
    at async FSWatcher.<anonymous> (D:\Dev\WebDev\NextJS\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\dist\index.js:511:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Dev\\WebDev\\NextJS\\tina-cloud-starter\\node_modules\\tina-graphql-gateway-cli\\dist\\index.js',
    'D:\\Dev\\WebDev\\NextJS\\tina-cloud-starter\\node_modules\\tina-graphql-gateway-cli\\bin\\tina-gql'
  ]
}
Done in 21.12s.
```

**Comment by DirtyF** [comment]
Hi Matteo, thanks for sharing. Please detail what leads to this error, your environment, etc. to give umore context. We didn't test under Windows yet 😊

**Comment by DirtyF** [comment]
Problem spotted, fix coming soon :)

**Comment by logan-anderson** [comment]
@MatteoGauthier we had a fix that we thought would resolve the problem but I just tested it and it looks like a new issues has started
```
Generating Tina config
Cannot find module 'C:\\Users\\Logan\\Documents\\GitHub\\tina-cloud-starter\\.tina\\__generated__\\temp\\schema.js'
Require stack:
- C:\Users\Logan\Documents\GitHub\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\dist\index.js
- C:\Users\Logan\Documents\GitHub\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\bin\tina-gql, exiting...
C:\Users\Logan\Documents\GitHub\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\dist\index.js:1
Error: Cannot find module 'C:\\Users\\Logan\\Documents\\GitHub\\tina-cloud-starter\\.tina\\__generated__\\temp\\schema.js'
Require stack:
- C:\Users\Logan\Documents\GitHub\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\dist\index.js
- C:\Users\Logan\Documents\GitHub\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\bin\tina-gql
    at compile (C:\Users\Logan\Documents\GitHub\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\dist\index.js:275:22)
    at async FSWatcher.<anonymous> (C:\Users\Logan\Documents\GitHub\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\dist\index.js:511:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Logan\\Documents\\GitHub\\tina-cloud-starter\\node_modules\\tina-graphql-gateway-cli\\dist\\index.js',
    'C:\\Users\\Logan\\Documents\\GitHub\\tina-cloud-starter\\node_modules\\tina-graphql-gateway-cli\\bin\\tina-gql'
  ]
}
Done in 23.42s.
```


any ideas how to fix this one  @jeffsee55 ?

**Comment by DirtyF** [comment]
@logan-anderson I still see double slashes in the path, are you using latest version?
Thought https://github.com/tinacms/tina-graphql-gateway/pull/177 wold fix the path on Windows.

**Comment by logan-anderson** [comment]
I did `npm i tina-graphql-gateway` So I thought I would be on the latest

**Comment by jamespohalloran** [comment]
Latest version the CLI too? https://www.npmjs.com/package/tina-graphql-gateway-cli (This might be a dev-dependency)

**Comment by logan-anderson** [comment]
@jamespohalloran Yes tried on the latest version of that as well.

**Comment by logan-anderson** [comment]
I think I tracked down the issue. We are not handling windows when using  [the fast-glob package](https://www.npmjs.com/package/fast-glob) should have a fix in soon

**Comment by logan-anderson** [comment]
@MatteoGauthier This should be fixed now on the latest version. Let us know if you run into any more issues and thanks for letting us know about this one.

**Comment by abrown2644** [comment]
On Windows as well and getting same error currently

```PS C:\code\practice\tina-cloud-starter> yarn dev
yarn run v1.22.10
$ yarn tina-gql server:start -c "next dev"
$ C:\code\practice\tina-cloud-starter\node_modules\.bin\tina-gql server:start -c "next dev"

Started Filesystem GraphQL server on port: 4001
Generating Tina config
Cannot find module 'C:\\code\\practice\\tina-cloud-starter\\.tina\\__generated__\\temp\\schema.js'
Require stack:
- C:\code\practice\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\dist\index.js
- C:\code\practice\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\bin\tina-gql, exiting...
C:\code\practice\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\dist\index.js:1
Error: Cannot find module 'C:\\code\\practice\\tina-cloud-starter\\.tina\\__generated__\\temp\\schema.js'
Require stack:
- C:\code\practice\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\dist\index.js
- C:\code\practice\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\bin\tina-gql
    at compile (C:\code\practice\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\dist\index.js:276:22)
    at async FSWatcher.<anonymous> (C:\code\practice\tina-cloud-starter\node_modules\tina-graphql-gateway-cli\dist\index.js:519:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\code\\practice\\tina-cloud-starter\\node_modules\\tina-graphql-gateway-cli\\dist\\index.js',
    'C:\\code\\practice\\tina-cloud-starter\\node_modules\\tina-graphql-gateway-cli\\bin\\tina-gql'
  ]
}
Done in 11.50s.

**Comment by DirtyF** [comment]
@abrown2644 What version of the tina-graphql package are you using?

**Comment by logan-anderson** [comment]
@abrown2644 I believe the latest version is `0.2.14` can you try `yarn add tina-graphql-gateway@latest` and then relaunch the dev server?

**Comment by B-Stewart** [comment]
Had to bump to the following to get latest master to work, `tina-graphql-gateway` wasn't enough. Needed the cli too.

```
"tina-graphql-gateway-cli": "0.2.45"
"tina-graphql-gateway": "0.2.14"
```

**Comment by DirtyF** [comment]
@B-Stewart right should be `content\posts` thanks for the feedback. Packages bump is on its way.

**Comment by B-Stewart** [comment]
Opened up a new ticket related to my duplicate path issue as it's kinda related to cross platform path handling, but needs to be fixed in the graphql package https://github.com/tinacms/tina-graphql-gateway/issues/259

**Comment by DirtyF** [comment]
We just released a new version of the package @MatteoGauthier and @B-Stewart please upgrade and tell us if that fixes your issue.

**Comment by B-Stewart** [comment]
Bumping to `"tina-graphql-gateway-cli": "0.2.49"` now gives me this error using npm
```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:packages/tina-graphql-helpers
```

yarn allows me to choose the package to install instead of crashing
```
Couldn't find any versions for "tina-graphql-helpers" that matches "workspace:packages/tina-graphql-helpers"
? Please choose a version of "tina-graphql-helpers" from this list: 0.0.22
```

And the duplicate issue https://github.com/tinacms/tina-graphql-gateway/issues/259 is still happening for me when I get it running again using yarn.

**Comment by calvary-tucson** [comment]
This might be related. Just forked the repository on Windows and ran `yarn install` and then `yarn dev` and got this error:

```
D:\Development\tina-cloud-starter>yarn dev
yarn run v1.22.10
$ yarn tina-gql server:start -c "next dev"
$ D:\Development\tina-cloud-starter\node_modules\.bin\tina-gql server:start -c "next dev"

Started Filesystem GraphQL server on port: 4001
Generating Tina config
Compiling...
Tina config ======> D:\Development\tina-cloud-starter\.tina\__generated__\config
Building schema...
Generating types...
Typescript types => D:\Development\tina-cloud-starter/.tina/__generated__/types.ts
GraphQL types ====> D:\Development\tina-cloud-starter/.tina/__generated__/schema.gql
node:events:355
      throw er; // Unhandled 'error' event
      ^

Error: spawn next ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn next',
  path: 'next',
  spawnargs: [ 'dev' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by logan-anderson** [comment]
@B-Stewart thanks for your report! There was an internal error with the way we where publishing our packages. This should be fixed if you update to the latest versions. I have made a PR that will force this https://github.com/tinacms/tina-cloud-starter/pull/91.
If you want to upgrade now you can run
```bash
yarn upgrade-interactive
```
and chose all the tina packages. 

You can also wait for the PR to me merged and then update your fork. 

@calvary-tucson that might be related as well. We will do some internal testing with a windows machine sometime this week. For now you could also try updating and see if the Issue persists.

**Comment by calvary-tucson** [comment]
@logan-anderson the update to the packages fixed path issue for me. Thanks!

The other problem I posted about might has something to do with the script command. I think it has something do to with the "-c" of the "yarn tina-gql server:start -c \"next dev\"" -- I know if I run the commands separately in different command prompts such as "yarn tina-gql server:start" in one and "yarn next dev" in another. Everything seems like it is working. Not sure if this helps.

**Comment by ghowardMSD** [comment]
I just forked from main that includes PR #91 and I'm getting this error on Windows:-
```
$ yarn tina-gql server:start -c "next dev"
$ D:\Projects\Github\tina-cloud-starter\node_modules\.bin\tina-gql server:start -c "next dev"

Started Filesystem GraphQL server on port: 4001
Visit the playground at http://localhost:4001/altair/
Generating Tina config
Compiling...
Transpiling...
Tina config ======> D:\Projects\Github\tina-cloud-starter\.tina\__generated__\config
Done Compiling...
Generating types...
Typescript types => D:\Projects\Github\tina-cloud-starter/.tina/__generated__/types.ts
GraphQL types ====> D:\Projects\Github\tina-cloud-starter/.tina/__generated__/schema.gql
node:events:353
      throw er; // Unhandled 'error' event
      ^

Error: spawn next ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:269:19)
    at onErrorNT (node:internal/child_process:467:16)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:275:12)
    at onErrorNT (node:internal/child_process:467:16)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn next',
  path: 'next',
  spawnargs: [ 'dev' ]
}

```

**Comment by jeffsee55** [comment]
@ghowardMSD I think you're running into what @calvary-tucson mentioned, you just need to run those commands in separate windows:
```sh
yarn tina-gql server:start
```
And in another terminal:
```sh
yarn next dev
```
---

@calvary-tucson I think the issue you're seeing is unrelated to the terminal problem, we're likely just not building that path properly, we'll take a look.

**Comment by ghowardMSD** [comment]
Yes, it does start ok when I run in separate windows and then I get the Pedro path issue.

**Comment by mitchmac** [comment]
Poking at the command issue after someone ran into it while checking out Tina, I tried [concurrently](https://www.npmjs.com/package/concurrently) and it seemed to work:

`"dev": "concurrently \"tina-gql server:start\" \"next dev\""`

The order of initial output may be a bit confusing though:
![Screen Shot 2021-07-16 at 2 47 07 PM](https://user-images.githubusercontent.com/618212/125989460-5d2411dc-e1f9-44f0-8b8c-4880892a8b55.png)

**Comment by jeffsee55** [comment]
@mitchmac  The problem with concurrently is during CI, we wouldn't know when to shut down the GraphQL server. I believe James was playing around with this a while back but I don't think he got it all the way sorted out.

**Comment by mitchmac** [comment]
@jeffsee55 Do we actually need to worry about CI right now for this, if we only changed the "dev" command? CI would be using build & export?

**Comment by jeffsee55** [comment]
@mitchmac Sure, it's just a pattern. They can also just run two processes.

**Comment by jeffsee55** [comment]
Related to https://github.com/tinacms/tinacms/issues/1951

**Comment by mystrdat** [comment]
Concurrently loads the app but renders as 404 and some SSR error using `"dev": "concurrently \"tinacms server:start\" \"next dev\"",`
![image](https://user-images.githubusercontent.com/1652895/128158573-75bb5960-b678-4b3f-8bc0-e22d87748b80.png)

**Comment by logan-anderson** [comment]
@mystrdat There was a couple issues with the navigation that have been fixed. Is your Fork up to date with the latest changes in the starter?

**Comment by mystrdat** [comment]
Yes, I just cloned current main. If i `yarn` install it and run `yarn dev`, it stops as it does for https://github.com/tinacms/tina-cloud-starter/issues/52#issuecomment-870960753

If I run `concurrently \"tinacms server:start\" \"next dev\"` it loads but fails with the errors in the image above.
If I add `tina-graphql-gateway tina-graphql-gateway-cli` packages and run `concurrently \"tina-gql server:start\" \"next dev\"`, it fails as follows

```
[0] Started Filesystem GraphQL server on port: 4001
[0] Visit the playground at http://localhost:4001/altair/
[1] event - compiled successfully
[0] Generating Tina config
[0] Compiling...
[0] Transpiling...
[0] Cannot read property 'collections' of undefined
[0] tina-gql server:start exited with code 0
```

**Comment by logan-anderson** [comment]
@mystrdat  Thanks for the details. Mind trying `concurrently \"tinacms server:start\" \"next dev\` in your scripts instead?

We changed the name of the command to start the server from `tina-gql` to `tinacms`

**Comment by mystrdat** [comment]
I did try those, mentioned them above, that results are in the image I posted. It build but 404s on frontend with the SSR errors.

**Comment by jeffsee55** [comment]
@mystrdat are you still importing `defineSchema` from the older `tina-graphql-gateway-cli`? It should be from `@tinacms/cli`:

```js
import { defineSchema } from '@tinacms/cli'
```

**Comment by mystrdat** [comment]
`defineSchema` is imported from '@tinacms/cli' as you mention, I'm using the latest `main` where it is as such. I've only tried `tina-graphql-gateway-cli` because others mentioned it before but that didn't work either.

**Comment by jeffsee55** [comment]
Ok just wondering because `tina-gql server:start exited with code 0` indicates you're running things with `tina-graphql-gateway-cli`, `tina-gql` was our old bin command, `tinacms` is the new one. The only commands you need are outlined [here](https://tina.io/docs/cli-overview/). 

To better debug this, can you run:

```sh
yarn tinacms server:start
```
And checkout `http://localhost:4001/altair. If you see a GraphQL GUI you should be able to run queries on it. That would at least tell us that the GraphQL portion is working.

**Comment by mystrdat** [comment]
That was from when I tried `tina-graphql-gateway-cli`, I described that in the comment. `http://localhost:4001/altair/` works.

**Comment by mitchmac** [comment]
Per @logan-anderson this should be ok but exposes issues deeper into use

**Comment by logan-anderson** [comment]
The deeper issue should be fixed now as well. Everything should work as expected on windows the same as unix
